version: "3.8"

services:
  postgres:
    image: postgres:14.4
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gravenDb
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5433:5432"
    volumes:
      - demo_pggdata:/var/lib/postgresql/data

volumes:
  demo_pggdata:
